### ISSUE TITLE
Re-work betting strategy code to work with `DeployableAgent.calculate_bet_amount`

### ISSUE THREAD

**Issue by evangriffiths** [gnosis/prediction-market-agent-tooling#104]
See betting strategies in prediction_market_agent_tooling/tools/betting_strategies/

These currently contain market-specific code. They should be refactored such that we could add a 'betting strategy' enum which could be passed to `DeployableAgent.calculate_bet_amount`, to get a bet amount for any betting strategy and any market type.

Currently this is hard-coded to return `market.get_tiny_bet_amount()`.

**Comment by kongzii** [comment]
But because `calculate_bet_amount` is just a method of class that needs to be subclassed, it's easy to change the strategy, for example in EVO:

![Screenshot by Dropbox Capture](https://github.com/gnosis/prediction-market-agent-tooling/assets/15619339/9a8dd67b-d83b-41fa-88c5-84179ae58eb4)

If we introduce enum, it will be easy to switch between built-in strategies, but not so easy to introduce new, experimental ones in agent itself.

Just something to keep in mind while implementing this, would be nice to have best of both worlds.

**Comment by evangriffiths** [comment]
Done!
