### ISSUE TITLE
Run Olas trader by ourself

### ISSUE THREAD

**Issue by kongzii** [gnosis/prediction-market-agent-tooling#146]
It seems like the way to do this is to spin up the VM and run `run_service.sh` from the quick start repo.

But I suggest we also add [GC Logging driver ](https://docs.docker.com/config/containers/logging/gcplogs/) so we can monitor the app within our GCP (our main motivation is to have logs and alerts based on error logs from the service or if the service stops for some reason).

**Comment by gabrielfior** [comment]
This probably involves some combination of
- Forking the trader-quickstart repo (https://github.com/valory-xyz/trader-quickstart)
- Adapting the logging part of things and redirecting that to GCP (I suggest Loguru for logging management)
- Make the `start_service.sh` startable whenever this gets deployed (instead of starting it manually)
- (Optional) Add that to our Streamlit dashboard and/or Dune dashboard

**Comment by kongzii** [comment]
I think this can be closed in favor of creating our own Olas-powered agent from one of our agents instead of just running their trader-quickstart. If someone disagrees, let's re-open and discuss.
