### ISSUE TITLE
Add support for Safe in transactions

### ISSUE THREAD

**Issue by kongzii** [gnosis/prediction-market-agent-tooling#148]
Having funds in Safe is safer as we can configure things like maximum withdraw amount per day, recovery, etc. In the future we want our agents to use Safe to store their funds instead of plain private key.

**Comment by gabrielfior** [comment]
Like this approach - I would also note that Olas uses Safe under-the-hood for all agents, so I would assume we can either a. copy-paste everything or, even better, b. use their interface for creating Safe accounts automatically for agents.

**Comment by gabrielfior** [comment]
I think we can definitely reuse something over start from scratch.
In my head, following options (in order of preference) make sense:

1 - Add Open-Autonomy as dependency to PMAT (https://docs.autonolas.network/open-autonomy/api/contracts/gnosis_safe_proxy_factory/contract/) and reuse some of their SafeContracts classes, so that we are able to deploy a Safe (via Safe factory) and send txs to the safe
2 - If above not possible, we can try to re-use old Python scripts to interact with Safe (https://github.com/safe-global/safe-eth-py/tree/69f1ee3263086403f6017effa0841c6a2fbba6d6/gnosis/safe). This is a bit risky (could work only for old versions), but we could test it out. I'm asking the Safe team about option 2 currently.
3 - If none of the above works, we can have a small Typescript server running somewhere, which accepts requests and wraps the Safe functionality.

**Comment by gabrielfior** [comment]
Found an interesting implementation using `safe-eth-py` (https://github.com/safe-global/safe-eth-py/blob/main/gnosis/safe/tests/safe_test_case.py#L225), which is also used by Polywrap's AutoTx (https://github.com/polywrap/AutoTx/blob/main/autotx/utils/ethereum/SafeManager.py). I'll probably follow a similar path.

**Comment by kongzii** [comment]
Do you know if it will be possible to somehow reuse our current code? E.g. all the functions accepting `private key` to also support Safe?

**Comment by gabrielfior** [comment]
Closed by #200
