### ISSUE TITLE
OmenAgentMarket Pydantic model breaks for binary markets which have outcomes different than "Yes" and "No"

### ISSUE THREAD

**Issue by gabrielfior** [gnosis/prediction-market-agent-tooling#173]
Example - 
https://aiomen.eth.limo/0x57c6bab1ba758d911f11e67ef323acebcfca04b7#/0x57c6bab1ba758d911f11e67ef323acebcfca04b7

Outcomes = "Yes, USDT ..." and "No, USDT ..."

Error stack:
```
/home/gabrielfior/miniconda3/envs/PMA/lib/python3.10/site-packages/prediction_market_agent_tooling/markets/omen/omen.py:170: in from_data_model
    p_yes=model.p_yes,

>       true_index = self.outcomes.index(OMEN_TRUE_OUTCOME)
E       ValueError: 'Yes' is not in list
```

Code to reproduce (part of another test)
```
    subgraph_handler = OmenSubgraphHandler()
    market_id = HexAddress(HexStr('0x57c6bab1ba758d911f11e67ef323acebcfca04b7'))
    market = subgraph_handler.get_omen_market(market_id)
    omen_agent_market = OmenAgentMarket.from_data_model(market) # problem here
```

From my understanding, the market above is still a binary market, but our Pydantic model is too strict when validating.

**Comment by kongzii** [comment]
Not a bug with Pydantic, but in our code, from the error you see:

```
/home/gabrielfior/miniconda3/envs/PMA/lib/python3.10/site-packages/prediction_market_agent_tooling/markets/omen/omen.py:170: in from_data_model
    p_yes=model.p_yes,

>       true_index = self.outcomes.index(OMEN_TRUE_OUTCOME)
E       ValueError: 'Yes' is not in list
```

That happens in https://github.com/gnosis/prediction-market-agent-tooling/blob/36fdc5123167e6568aa96e355f91e4294c80d668/prediction_market_agent_tooling/markets/omen/data_models.py#L237

Because `OMEN_TRUE_OUTCOME` (which is equal to `Yes`) isn't in the list.

The problem is that you can create a market with arbitrary outcomes, but if they aren't equal to `Yes` and `No`, we don't know what should be `p_yes` because we don't know which outcome points to `Yes`. Theoretically, the market can have 2 outcomes and be binary, but they don't have to be Yes and No.

There is a related issue to this: https://github.com/gnosis/prediction-market-agent-tooling/issues/41

**Comment by kongzii** [comment]
I wonder how you get that market btw?

Because in `get_omen_binary_markets` there is a default filter for:

https://github.com/gnosis/prediction-market-agent-tooling/blob/36fdc5123167e6568aa96e355f91e4294c80d668/prediction_market_agent_tooling/markets/omen/omen_subgraph_handler.py#L275

So agents should never see markets that don't have `Yes` and `No` outcomes.

**Comment by gabrielfior** [comment]
That market was one of the markets with highest liquidity, selected via Omen UI.
We can of course decide NOT to bet in such markets, but they are ofc binary (indicated by the slot count) and the fact that they don't have [YES,NO] is in my mind just a technicality.

**Comment by gabrielfior** [comment]
This won't be prioritized at this time because our agents are mostly interested in markets created by other agents that are hard coded to have [YES,NO] as outcomes. Possible changes in this behavior will probably impact the whole codebase (for ex, the `p_yes` definition), hence will not be a priority at this time.
