### ISSUE TITLE
Improve `get_kelly_bet_full` in case`yes_outcome_pool_size == no_outcome_pool_size`

### ISSUE THREAD

**Issue by gabrielfior** [gnosis/prediction-market-agent-tooling#413]
In this case, following logic is triggered
```
  if x == y:
      # Add a delta to prevent division by zero
      y += 1e-10
```
for an example market (https://presagio.pages.dev/markets?id=0x5b1457bb7525eed03d3c78a542ce6d89be6090e1), token amounts are ~0.99e18 and 0.49e18. If I hypothetically had `yes_amount` and `no_amount` equal (== 1e18), an error would occur
```
get_kelly_bet_full(10e18, 10e18, 0.8,1, 1e18)
  File "<ipython-input-35-3e11064e21f4>", line 137, in get_kelly_bet_full
    kelly_bet_amount = numerator / denominator
                       ~~~~~~~~~~^~~~~~~~~~~~~
ZeroDivisionError: float division by zero
```

2 options come to mind:
1 - Instead of adding `y+= 1e-10`, multiply it by a small percentage, e.g. `y *= 1.001`
2 - Instead of changing y and x artifically, trigger `get_kelly_bet_simplified` - in my quick experiments, this yields smaller bet amounts than `kelly_full`.

**Comment by kongzii** [comment]
It seems like a bad edge case because of huge numbers, where adding 1e-10 doesn't do anything (even with Decimals):

![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/0c7ec0a7-1e3f-460a-9737-13b9c52331ed)

But doing `* 1.001` also doesn't feel right:

![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/6e1e7dd3-1498-441f-84ba-884fe15fb134)

That would add `9999999999998898.65875957`, which is a huge number as well, but we don't know the currency.

I am keen to see some fix proposals for this, but I'm not sure if it would be easy, I didn't expect that math operations like `*`, `**`,`/` would work fine with numbers like `10e18` (or very tiny ones like `10e-18`).

> token amounts are ~0.99e18 and 0.49e18

From the code seems like Evan assumes that outcome token pool is in market's currency (xDai/USD), not Wei, so this shouldn't happen in practice:

![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/42d3d7ba-1a4a-4855-ad1a-c8828d1b9d1b)

**Comment by gabrielfior** [comment]
> From the code seems like Evan assumes that outcome token pool is in market's currency (xDai/USD), not Wei, 

This diverges from the derivation mentioned in the docstring. The units cancel out, but it's paramount that the `bet_amount` is also given in the same currency as the token reserves. In my mind, it's safer to use ints everywhere, or even better, BigInts (a thing in TS, but supported naturally in Python).

> I am keen to see some fix proposals for this, but I'm not sure if it would be easy,

The simplified version of the `kelly_bet` would not diverge in the case where `n_tokens_yes` == `n_tokens_no`. Why would artificially increasing/decreasing the pool sizes be advisable vs this option? I'm not sure which one is better.

**Comment by evangriffiths** [comment]
> From the code seems like Evan assumes that outcome token pool is in market's currency (xDai/USD), not Wei, so this shouldn't happen in practice

Yes, that's right. And `bet_amount` too. So we wouldn't see this problem in practice. But the `y *= 1 + 1e-10` option seems like a good fix to me for the general case

**Comment by kongzii** [comment]
> it's safer to use ints everywhere,

You don't need to convert floats to integers in Python, if you want precision, you can use Decimals, we discussed it on Slack https://gnosisinc.slack.com/archives/C06NHPV2WQP/p1726573795023199?thread_ts=1726569077.755189&cid=C06NHPV2WQP 

> The simplified version of the kelly_bet would not diverge in the case where n_tokens_yes == n_tokens_no. Why would artificially increasing/decreasing the pool sizes be advisable vs this option? I'm not sure which one is better.

Because:

```
get_kelly_bet_simplified(10, 0.5, 1, 1)=SimpleBet(direction=True, size=5.0)
get_kelly_bet_full(10, 10, 1, 1, 10)=SimpleBet(direction=True, size=10.0)
```

**Comment by gabrielfior** [comment]
To be implemented in https://github.com/gnosis/prediction-market-agent-tooling/issues/377
