### ISSUE TITLE
Seer - add subgraph to SubgraphHandler

### ISSUE THREAD

**Issue by gabrielfior** [gnosis/prediction-market-agent-tooling#501]
- Check if subgraph contains required functions (e.g. `getMarkets`, `getTradesFromUser`, etc) and add them to SubgraphHandler
- If not, deploy new subgraph
- Additional reference - see (https://thegraph.com/explorer/subgraphs/AAA1vYjxwFHzbt6qKwLHNcDSASyr1J1xVViDH8gTMFMR?view=Query&chain=arbitrum-one) for Algebra pools, we might need a different source for all pools for a given (outcomeToken, collateralToken) pair

**Comment by kongzii** [comment]
Instead of adding seer to `OmenSubgraphHandler`, I vote for a new class, `SeerSubgraphHandler`. [See this comment ](https://github.com/gnosis/prediction-market-agent-tooling/pull/490/files#r1795285026)for the reasoning; TLDR is that OmenSubgraphHandler is already crowded, and it is hard to tell what's going on.

**Comment by gabrielfior** [comment]
Agree with `SeerSubgraphHandler `
